//! Restoring a `.sql` file, against a real Postgres.
//!
//! Every case here is a way a dump written by another client fails when it is
//! restored somewhere else. They are not hypothetical: each one is a step of
//! the report this path was built for — a Prisma database exported with
//! TablePlus and imported on another server.
//!
//! 1. **Order.** The dump is written table by table, alphabetically, so
//!    `order_items` is written before `orders` and its rows reach the server
//!    before the rows they point at. A self-referencing column makes it
//!    unsolvable by reordering at all.
//! 2. **Roles.** `OWNER TO` names a role that exists on the other server.
//! 3. **Sequences.** The restore succeeds and the *application* then fails,
//!    because the sequence behind an `autoincrement()` key is still at 1.
//! 4. **The file's own transaction.** This application's safe export writes
//!    `BEGIN;` and `COMMIT;`. Run inside the importer's transaction, that
//!    `COMMIT` ends it partway through and the all-or-nothing promise is gone.
//!
//! Skipped unless `RASHBASE_PG_PASSWORD` is set, so `cargo test` on a machine
//! with no database still passes.
//!
//! ```sh
//! RASHBASE_PG_PASSWORD=... cargo test --test import_restore -- --nocapture
//! ```

use rashbase_studio_lib::drivers::{
    ConnectionConfig, DbState, ImportProgress, ImportRequest, SslMode,
};

/// The schema a case works in.
///
/// One per test rather than one shared: `cargo test` runs them concurrently
/// against the same database, and a shared schema means each test's `drop
/// schema … cascade` takes another test's tables out from under it.
fn schema_for(id: &str) -> String {
    format!("rb_import_{}", id.replace('-', "_"))
}

fn env_config(id: &str) -> Option<(ConnectionConfig, String)> {
    let password = std::env::var("RASHBASE_PG_PASSWORD").ok()?;
    Some((
        ConnectionConfig {
            id: id.into(),
            driver: "postgres".into(),
            name: "import test".into(),
            host: std::env::var("RASHBASE_PG_HOST").unwrap_or_else(|_| "localhost".into()),
            port: std::env::var("RASHBASE_PG_PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(5432),
            user: std::env::var("RASHBASE_PG_USER").unwrap_or_else(|_| "postgres".into()),
            database: std::env::var("RASHBASE_PG_DATABASE").unwrap_or_else(|_| "postgres".into()),
            ssl_mode: SslMode::Prefer,
            environment: Some("local".into()),
            parent_id: None,
            require_biometric: false,
            ssh: None,
        },
        password,
    ))
}

/// Counts nothing and remembers nothing. The ticks are the window's business.
struct Quiet;
impl ImportProgress for Quiet {
    fn tick(&mut self, _: usize, _: u64, _: &str) {}
}

fn request(path: &str) -> ImportRequest {
    ImportRequest {
        path: path.to_string(),
        hold_foreign_keys: true,
        skip_ownership: true,
        skip_migration_history: true,
        reset_sequences: true,
        orm: Some("Prisma".to_string()),
        total_statements: 0,
    }
}

fn write(name: &str, body: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("rashbase-import-it-{}", uuid::Uuid::new_v4()));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join(name);
    std::fs::write(&path, body).unwrap();
    path
}

/// One integer out of the database, for the assertions below.
async fn number(state: &DbState, id: &str, sql: &str) -> i64 {
    let results = state.execute(id, sql, None).await.unwrap();
    let cell = results[0].rows[0][0].as_ref().unwrap();
    cell.parse::<i64>().unwrap()
}

async fn connect(id: &str) -> Option<(DbState, String)> {
    let (config, password) = env_config(id)?;
    let schema = schema_for(id);
    let state = DbState::default();
    state.connect(&config, Some(&password), None).await.unwrap();
    state
        .execute(id, &format!("drop schema if exists {schema} cascade"), None)
        .await
        .unwrap();
    Some((state, schema))
}

/// A dump in the shape TablePlus writes: relations alphabetical, every table's
/// rows written with its own definition, roles and history included.
///
/// `order_items` comes before `orders`, so its first row points at a row that
/// is not there yet. `orders.parent_id` points back at `orders`, so no
/// reordering of the file could have saved it.
fn tableplus_shaped(schema: &str) -> String {
    format!(
        "-- Rashbase import test\n\
         CREATE SCHEMA IF NOT EXISTS {schema};\n\
         \n\
         CREATE TABLE {schema}.order_items (\n\
         \x20   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n\
         \x20   order_id integer NOT NULL,\n\
         \x20   note text,\n\
         \x20   PRIMARY KEY (id)\n\
         );\n\
         CREATE TABLE {schema}.orders (\n\
         \x20   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n\
         \x20   parent_id integer,\n\
         \x20   PRIMARY KEY (id)\n\
         );\n\
         CREATE TABLE {schema}._prisma_migrations (id text NOT NULL PRIMARY KEY);\n\
         \n\
         ALTER TABLE {schema}.order_items\n\
         \x20   ADD CONSTRAINT order_items_order_id_fkey\n\
         \x20   FOREIGN KEY (order_id) REFERENCES {schema}.orders(id);\n\
         ALTER TABLE {schema}.orders\n\
         \x20   ADD CONSTRAINT orders_parent_id_fkey\n\
         \x20   FOREIGN KEY (parent_id) REFERENCES {schema}.orders(id);\n\
         \n\
         ALTER TABLE {schema}.orders OWNER TO rb_role_that_is_not_here;\n\
         GRANT SELECT ON {schema}.orders TO rb_role_that_is_not_here;\n\
         \n\
         -- rows, in the order the tables were written\n\
         INSERT INTO {schema}.order_items (id, order_id, note) VALUES (1, 100, 'a;b');\n\
         INSERT INTO {schema}.order_items (id, order_id, note) VALUES (2, 101, E'C:\\\\');\n\
         INSERT INTO {schema}.orders (id, parent_id) VALUES (100, 101);\n\
         INSERT INTO {schema}.orders (id, parent_id) VALUES (101, NULL);\n\
         INSERT INTO {schema}._prisma_migrations (id) VALUES ('20240101_init');\n"
    )
}

/// The report, end to end: the file that fails everywhere else applies here,
/// and the three things that make it fail are each visibly handled.
#[tokio::test(flavor = "multi_thread")]
async fn a_dump_written_child_first_restores() {
    let id = "import-order";
    let Some((state, schema)) = connect(id).await else {
        eprintln!("skipped: RASHBASE_PG_PASSWORD not set");
        return;
    };

    let path = write("shop.sql", &tableplus_shaped(&schema));
    let summary = state
        .import(id, "job", &request(path.to_str().unwrap()), &mut Quiet)
        .await
        .expect("the file should apply");

    // The rows went in in the file's own order, which no ordering could fix.
    assert_eq!(number(&state, id, &format!("select count(*) from {schema}.order_items")).await, 2);
    assert_eq!(number(&state, id, &format!("select count(*) from {schema}.orders")).await, 2);

    // Two role statements and one migration row, and nothing else.
    assert_eq!(summary.skipped, 3);

    // The history table is there; the other server's account of it is not.
    assert_eq!(
        number(&state, id, &format!("select count(*) from {schema}._prisma_migrations")).await,
        0
    );

    // The half nobody sees until the application's next insert.
    assert_eq!(summary.sequences_reset, 2);
    let next = number(
        &state,
        id,
        &format!("select nextval(pg_get_serial_sequence('{schema}.orders', 'id'))"),
    )
    .await;
    assert!(next > 101, "the sequence must be past the keys the dump carried, got {next}");

    // A value with a semicolon in it survived the split.
    assert_eq!(
        state
            .execute(id, &format!("select note from {schema}.order_items where id = 1"), None)
            .await
            .unwrap()[0]
            .rows[0][0]
            .as_deref(),
        Some("a;b")
    );

    let _ = std::fs::remove_dir_all(path.parent().unwrap());
}

/// The all-or-nothing promise, tested where it actually gets broken: after the
/// file's own `COMMIT`. If that `COMMIT` ran, everything before it is already
/// committed and the rollback below cannot take it back.
#[tokio::test(flavor = "multi_thread")]
async fn a_refusal_after_the_files_own_commit_still_rolls_everything_back() {
    let id = "import-rollback";
    let Some((state, schema)) = connect(id).await else {
        eprintln!("skipped: RASHBASE_PG_PASSWORD not set");
        return;
    };

    let body = format!(
        "BEGIN;\n{}\nCOMMIT;\n\
         INSERT INTO {schema}.orders (id, parent_id) VALUES ('not a number', NULL);\n",
        tableplus_shaped(&schema)
    );
    let path = write("bad.sql", &body);

    let error = state
        .import(id, "job", &request(path.to_str().unwrap()), &mut Quiet)
        .await
        .expect_err("the last statement is not valid and must fail the import");

    // The server's own words, and the line of the file, kept apart.
    let rendered = serde_json::to_value(&error).unwrap();
    assert!(
        rendered["message"].as_str().unwrap().contains("invalid input syntax"),
        "the database's own words, got {rendered:?}"
    );
    assert!(rendered["context"].as_str().unwrap().starts_with("line "));

    // Nothing survived, including the schema the file created before its COMMIT.
    let present = number(
        &state,
        id,
        &format!("select count(*) from pg_namespace where nspname = '{schema}'"),
    )
    .await;
    assert_eq!(present, 0, "the file's own COMMIT must not have committed anything");

    let _ = std::fs::remove_dir_all(path.parent().unwrap());
}

/// pg_dump's default format. The rows arrive as a `COPY` data block, which is
/// not SQL and cannot be run as a statement at all.
#[tokio::test(flavor = "multi_thread")]
async fn a_copy_dump_streams_its_rows() {
    let id = "import-copy";
    let Some((state, schema)) = connect(id).await else {
        eprintln!("skipped: RASHBASE_PG_PASSWORD not set");
        return;
    };

    let body = format!(
        "CREATE SCHEMA {schema};\n\
         CREATE TABLE {schema}.items (\n\
         \x20   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n\
         \x20   parent_id integer REFERENCES {schema}.items(id),\n\
         \x20   note text\n\
         );\n\
         COPY {schema}.items (id, parent_id, note) FROM stdin;\n\
         1\t2\tone; with a semicolon\n\
         2\t\\N\t\\N\n\
         3\t1\ta\\ttab\n\
         \\.\n"
    );
    let path = write("pg.sql", &body);

    let summary = state
        .import(id, "job", &request(path.to_str().unwrap()), &mut Quiet)
        .await
        .expect("a COPY dump should apply");

    assert_eq!(summary.rows, 3);
    assert_eq!(number(&state, id, &format!("select count(*) from {schema}.items")).await, 3);
    // Row 1 points at row 2, which the block had not reached yet.
    assert_eq!(
        number(&state, id, &format!("select parent_id from {schema}.items where id = 1")).await,
        2
    );
    // NULL and the string "\N" stayed tellable apart.
    assert_eq!(
        number(
            &state,
            id,
            &format!("select count(*) from {schema}.items where note is null")
        )
        .await,
        1
    );

    let next = number(
        &state,
        id,
        &format!("select nextval(pg_get_serial_sequence('{schema}.items', 'id'))"),
    )
    .await;
    assert!(next > 3, "got {next}");

    let _ = std::fs::remove_dir_all(path.parent().unwrap());
}

/// Every switch off. The same file must now fail exactly the way it fails in
/// every other client — which is what makes the switches worth having.
#[tokio::test(flavor = "multi_thread")]
async fn the_same_file_fails_with_the_switches_off() {
    let id = "import-unguarded";
    let Some((state, schema)) = connect(id).await else {
        eprintln!("skipped: RASHBASE_PG_PASSWORD not set");
        return;
    };

    let path = write("shop.sql", &tableplus_shaped(&schema));
    let mut req = request(path.to_str().unwrap());
    req.hold_foreign_keys = false;
    req.skip_ownership = false;
    req.skip_migration_history = false;
    req.reset_sequences = false;

    let error = state
        .import(id, "job", &req, &mut Quiet)
        .await
        .expect_err("without the switches this file is the bug report");

    let rendered = serde_json::to_value(&error).unwrap();
    let message = rendered["message"].as_str().unwrap();
    // Whichever comes first — the missing role or the key with nothing behind
    // it — both are what the switches exist to get past.
    assert!(
        message.contains("does not exist") || message.contains("violates foreign key constraint"),
        "got {message}"
    );

    let _ = std::fs::remove_dir_all(path.parent().unwrap());
}
